### ISSUE TITLE
not working in partial views

### ISSUE THREAD

**Issue by aliramadan8** [NonFactors/AspNetCore.Lookup.Web#7]
for some unknown reason for me ,the lookup control in partial view is not working and is shown as below image 
![image](https://user-images.githubusercontent.com/24622815/93353569-5f5edc80-f83c-11ea-9147-baabfaf08e93.png)
this is the code below ,
```
<div class="col-lg-6">
    <form asp-controller="ivInvReservations"
          asp-action="Create"
          asp-route-returnurl="@ViewBag.ReturnUrl"
          asp-anti-forgery="false"
          method="post"
          id="FullForm">
        <div ID="dvItemID">
            <div class="form-group has-feedback  ">
                <label id="lblItemID" class="control-label ">@Localizer["SelectItemID"]</label>

                <div>

                    <div mvc-lookup="lookup" id="lkpItemID" title=@Localizer["SearchPageItemsTitle"] url="/Inventory/Items/AllPurchasingItems" class="lkpivItemDetails" add-handler="true"></div>
                    <input id="lblItemIDName" type="text" class="form-control  " placeholder="Item ID" readonly />
                    <input id="txtItemID" class="form-control required " type="text" autocomplete="off" placeholder="Item ID" />
                </div>

            </div>
        </div>
    </form>
</div>
```

if i used same code in non partialview it work perfectly 

![image](https://user-images.githubusercontent.com/24622815/93353717-874e4000-f83c-11ea-81cb-70af926e8fed.png)

any thoughts here ,i know mostly it is not control related ,but any thoughts ?

**Comment by Muchiachio** [comment]
Maybe lookup partial got included twice? There should only be one lookup partial in the DOM.

**Comment by aliramadan8** [comment]
yes this was the exact cause , thanks
