### ISSUE TITLE
Not able to get it working in Razor Pages

### ISSUE THREAD

**Issue by Mapel** [NonFactors/AspNetCore.Lookup.Web#8]
Hi,

I am not able to translate the MVC-example to Razor pages.

```
    [HttpGet]
    public JsonResult People(LookupFilter filter)
    {
        PeopleLookup lookup = new PeopleLookup(Context);
        lookup.Filter = filter;

        return Json(lookup.GetData());
    }
```

I change this method to this:
```
    public JsonResult OnGetPeople(LookupFilter filter)
    {
        PeopleLookup lookup = new PeopleLookup(Context);
        lookup.Filter = filter;

        return new JsonResult(lookup.GetData());
    }
```

How do I bind the control to the action in the page model? The url-taghelper is not working and asp-page-handler is not recognized...

Thanks for your help.

**Comment by Muchiachio** [comment]
Lookup just makes the request to the url you provide. I'm not sure why razor pages ignores it.

**Comment by Mapel** [comment]
I found the solution. I needed to use the handler url:

```
   url="?handler=People"
```

You may want to add such example to your webpresentation.
